-----------------------------------------------------------
--------- AUTOGENERATED FILE, DO NOT EDIT -----------------
-----------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


entity tute0 is port(
	clk_clk, clk_reset_n: in std_ulogic;
	xx:	in u8; -- reg
	yy:	in u8; -- reg
	someUnused:	in u8; -- WIRE
	sum:	out u8; -- reg
	totalSum:	out u8; -- reg
	outXorWire:	out u8; -- WIRE
	outLatch:	out u8 -- Latch
	);
end entity;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


--#------- tute0 ------------------------------------
architecture rtl of tute0 is
	signal dg_o_sum: u8;	-- reg
	signal dg_o_totalSum: u8;	-- reg
	signal dg_o_outXorWire: u8;	-- WIRE
	signal dg_o_outLatch: u8;	-- LATCH!!!
	signal counter: u4;	-- reg
begin

	dg_comb_proc1_comb: process (all)
	begin
		dg_o_outLatch <= dg_o_outLatch; -- latch preload
		if (dg_boolToBit(xx = X"55") = '1') then
			dg_o_outLatch <= yy;
		end if;
	end process;

	MyProcess_comb: process (all)
		variable varSum: u8;
	begin
		dg_o_outXorWire <= X"00"; -- wire pre-zero-init
		varSum := X"00"; -- local-var zero-init
		varSum := (xx + yy);
		dg_o_outXorWire <= (xx xor yy);
	end process;

	MyProcess: process
		variable varSum: u8;
	begin
		wait until rising_edge(clk_clk)
		varSum := X"00"; -- local-var zero-init
		varSum := (xx + yy);
		dg_o_sum <= varSum;
		dg_o_totalSum <= (dg_o_totalSum + varSum);
		if (dg_boolToBit(counter = X"5") = '1') then
			dg_o_totalSum <= varSum;
		end if;
		counter <= counter + X"1";
		if clk_reset_n = '0' then
			dg_o_totalSum <= X"00";
			counter <= X"0";
		end if;
	end process;

	------[ output registers/wires/latches ] --------------
	sum <= dg_o_sum;
	totalSum <= dg_o_totalSum;
	outXorWire <= dg_o_outXorWire;
	outLatch <= dg_o_outLatch;
end;



