-----------------------------------------------------------
--------- AUTOGENERATED FILE, DO NOT EDIT -----------------
-----------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;

use work.mypack.all;

package myentities is
end package;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;

use work.mypack.all;

entity tute2 is port(
	clk_clk, clk_reset_n: in std_ulogic;
	memctl:	in MEM_CTL; -- reg
	memres:	out MEM_RES; -- reg
	resXorAnd:	out u8 -- WIRE
	);
end entity;

