-----------------------------------------------------------
--------- AUTOGENERATED FILE, DO NOT EDIT -----------------
-----------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


entity tute1_tb is  end entity;
architecture testbench of tute1_tb is
	signal success, done, error : std_ulogic := '0';
	signal reset_n, clk : std_ulogic := '0';
	signal counter : integer := 0;
	signal oout : u8;
begin
	success <= done and (not error);
	process begin
		clk <= '0';  wait for 5 ps;
		clk <= '1';  wait for 5 ps;
	end process;
	process begin
		wait until rising_edge(clk);
		counter <= counter + 1;
		if counter >= 10 then
			reset_n <= '1';
		end if;
	end process;
	test: entity work.tute1 port map(
		clk_clk => clk, clk_reset_n => reset_n,
		oout => oout 
	);
end;

