-----------------------------------------------------------
--------- AUTOGENERATED FILE, DO NOT EDIT -----------------
-----------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


entity MyAdder is port(
	clkAdd_clk, clkAdd_reset_n: in std_ulogic;
	x:	in u8; -- reg
	y:	in u8; -- reg
	zout:	out u8 -- reg
	);
end entity;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


entity tute1 is port(
	clk_clk, clk_reset_n: in std_ulogic;
	oout:	out u8 -- reg
	);
end entity;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


--#------- MyAdder ------------------------------------
architecture rtl of MyAdder is
	signal dg_o_zout: u8;	-- reg
begin

	main: process
	begin
		wait until rising_edge(clkAdd_clk)
		dg_o_zout <= (x + y);
	end process;

	------[ output registers/wires/latches ] --------------
	zout <= dg_o_zout;
end;



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


--#------- tute1 ------------------------------------
architecture rtl of tute1 is
	signal dg_o_oout: u8;	-- reg

	----- sub-unit signals -------------
		signal madd_x : u8;
		signal madd_y : u8;
		signal madd_zout : u8;
		signal madd2_x : u8;
		signal madd2_y : u8;
		signal madd2_zout : u8;
		signal madd2_clkAdd_clk, madd2_clkAdd_reset_n : std_ulogic;
begin

	main: process
	begin
		wait until rising_edge(clk_clk)
		madd_x <= X"01";
		madd_y <= X"02";
		madd2_y <= X"05";
		dg_o_oout <= (madd_zout + madd2_zout);
	end process;

	-------[ sub-units ]-----------
	madd : entity work.MyAdder port map(
		clkAdd_clk => clk_clk,
		clkAdd_reset_n => clk_reset_n,
		x => madd_x,
		y => madd_y,
		zout => madd_zout
	);
	madd2 : entity work.MyAdder port map(
		clkAdd_clk => madd2_clkAdd_clk,
		clkAdd_reset_n => madd2_clkAdd_reset_n,
		x => madd2_x,
		y => madd2_y,
		zout => madd2_zout
	);

	-------[ links ]----------
	madd2_clkAdd_clk <= clk_clk;
	madd2_clkAdd_reset_n <= clk_reset_n;
	madd2_x <= madd_zout;

	------[ output registers/wires/latches ] --------------
	oout <= dg_o_oout;
end;



