-----------------------------------------------------------
--------- AUTOGENERATED FILE, DO NOT EDIT -----------------
-----------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.desilog.all;


entity example1_tb is  end entity;
architecture testbench of example1_tb is
	signal done,error : std_ulogic := '0';
	signal reset_n,clk : std_ulogic := '0';
	signal counter : integer := 0;
	signal in_ry : u8;
	signal outa : u8;
	signal outb : u8;
begin
	process(clk, reset_n) begin
		in_ry <= X"00";
	end process;
	process begin
		clk <= '0';  wait for 5 ps;
		clk <= '1';  wait for 5 ps;
	end process;
	process begin
		wait until rising_edge(clk);
		counter <= counter + 1;
		if counter >= 10 then
			reset_n <= '1';
		end if;
	end process;
	test: entity work.Example1 port map(
		clk_clk => clk, clk_reset_n => reset_n,
		in_ry => in_ry ,
		outa => outa ,
		outb => outb 
	);
end;

